<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/>
    </parent>

    <groupId>cl.duoc.tienda</groupId>
    <artifactId>tienda-gamer-microservicios</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>tienda-gamer-microservicios</name>
    <description>Proyecto padre para los microservicios de Tienda Gamer</description>

    <modules>
        <module>usuario-service</module>
        <module>tienda-gamer-service</module>
        <module>inventario-service</module>
        <module>orden-service</module>
        <module>pago-service</module>
        <module>api-gateway</module>
        <module>eureka-server</module>
        <module>categoria-service</module>
        <module>proveedor-service</module>
        <module>carrito-service</module>
        <module>resena-service</module>
        <module>notificacion-service</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring-cloud.version>2025.1.1</spring-cloud.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <configuration>
                            <excludes>
                                <exclude>**/*Application.class</exclude>
                                <exclude>**/*DataInitializer.class</exclude>
                            </excludes>
                        </configuration>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
