server:
  port: ${PORT:8090}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: usuario-service
              uri: ${USUARIO_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/usuarios/**

            - id: tienda-gamer-service
              uri: ${TIENDA_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/productos/**

            - id: orden-service
              uri: ${ORDEN_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/ordenes/**

            - id: inventario-service
              uri: ${INVENTARIO_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/inventario/**

            - id: pago-service
              uri: ${PAGO_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/pagos/**
            - id: categoria-service
              uri: ${CATEGORIA_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/categorias/**
            - id: proveedor-service
              uri: ${PROVEEDOR_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/proveedores/**
            - id: carrito-service
              uri: ${CARRITO_SERVICE_URL:http://localhost:8087}
              predicates:
                - Path=/carritos/**
            - id: resena-service
              uri: ${RESENA_SERVICE_URL:http://localhost:8088}
              predicates:
                - Path=/resenas/**
            - id: notificacion-service
              uri: ${NOTIFICACION_SERVICE_URL:http://localhost:8089}
              predicates:
                - Path=/notificaciones/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
