server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: usuario-service
              uri: ${USUARIO_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/usuarios/**

            - id: tienda-gamer-service
              uri: ${TIENDA_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/productos/**

            - id: orden-service
              uri: ${ORDEN_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/ordenes/**

            - id: inventario-service
              uri: ${INVENTARIO_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/inventario/**

            - id: pago-service
              uri: ${PAGO_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/pagos/**

management:
  endpoints:
    web:
      exposure:
        include: health,info